### ALUNO: MAURO NOOBLATH   17/10/2020

### Método de Jacobi

__O método de Jacobi utiliza umaa sucessão de transformações ortogonais para produzir uma sequência de matrizes que se aproxima de uma matriz diagonal limite. Este método é utilizado para encontrar Autovalores e Autovetores dessas matrizes. Temos transformações similares ao que é feito abaixo__

<center>
    A<sub>k+1</sub> = J<sub>k</sub><sup>t</sup>A<sub>k</sub>J<sub>k</sub>

_Dada uma matriz A simétrica, ou seja A<sup>T</sup>=A onde A<sub>T</sub> é a transposta da Matriz A, faremos uma sequência de rotações:_
<center> 
    AJ<sub>1</sub> = A; A<sub>2</sub> = J<sub>1</sub><sup>t</sup>A<sub>1</sub>J<sub>1</sub>; ... ; A<sub>n+1</sub> = J<sub>n</sub><sup>t</sup>A<sub>n</sub>J<sub>n</sub>; 

_Veja que J é uma matriz de rotação.Dada uma rotação (p,q), temos as seguintes definições para J:_
<center>
    
j<sub>pp</sub> = j<sub>qq</sub> = cos($\phi$)
    
j<sub>pq</sub> = -j<sub>qp</sub> = sen($\phi$)
    
j<sub>ii</sub> = 1, 
    
j<sub>ij</sub> = 00, no resto 
    
</center>


_Um exemplo de uma matriz de ordem 3 é usado abaixo para ilustrar as definições acima, suponhamos que p seja igual a 2 e q igual a 3._

<center>
   $$
U= \left[
\begin{array}{ccc}
1 & 0 & 0  \\
0 & cos(\phi) & sin(\phi)\\
0 & -sin(\phi) & cos(\phi)\end{array}
\right]
$$

__Exemplificando o método implementado abaixo vamos extrair os autovalores de uma matriz 2x2__ 

\
<center>
   $$
A= \left[
\begin{array}{ccc}
7 & 2 \\
2 & 7 \end{array}
\right]
$$
    


__Temos uma matriz 2x2. Observe claramente que ela é uma matriz simétrica, ou seja $A = A^t$, portanto podemos aplicar o método de Jacobi.__

__Temos algumas equações que serão utilizadas durante a iteração que são dadas abaixo__

$$\phi = \frac{a_{qq} - a_{pp}}{2a_{pq}}$$
$$t = \frac{1}{\phi + sinal(\phi) \sqrt{\phi^2 +1}}  para  \phi \neq 0$$  
$$t = 1 para \phi = 0$$

$$\cos(\phi) = \frac{1}{\sqrt{1+t^2}}$$
$$\sin(\phi) = \frac{t}{\sqrt{1+t^2}}$$


**Considere os elementos fora da diagonal principal, veja que o maior elemento fora da diagonal principal é o a<sub>12</sub> portanto veja que p = 1 e q = 2**

_O elemento a<sub>qq</sub>, a<sub>pp</sub> e a<sub>pq</sub> é o elemento a<sub>22</sub>, a<sub>11</sub> e a<sub>12</sub> respectivamente._ 
\
\
_Logo a<sub>22</sub> = 7, a<sub>11</sub> = 7 e a<sub>12</sub> = 2 portanto calculando $\phi$  temos que: $$\phi = \frac{7 - 7}{2*2} = 0$$_
\
\
_Como $\phi = 0  \to  t = 1$_
\
_Logo cos(phi) que vamos chamar de c vai ser:_ $$c = \frac{1}{\sqrt{1+1}} \to c = \frac{2}{\sqrt{2}} = 0.7071$$
\
$$s = \frac{1}{\sqrt{1+1}} \to s = \frac{2}{\sqrt{2}} = 0.7071$$
\
_Vamos agora descobri a nossa matriz de rotação:_
 \
<center>
   $$
U= \left[
\begin{array}{ccc}
u_{11} & u_{12} \\
u_{21} & u_{22} \end{array}
\right]
$$
Como p = 1 e q = 2 e considerando as restrições discutidas sobre matriz de rotação acima, $$u_{pp} \to u_{11} \to \cos(\phi)$$
    $$u_{qq} \to u_{22} \to \cos(\phi)$$ $$u_{pq} = -u_{qp} \to u_{12} = \sin(\phi)    u_{21} = -\sin(\phi) $$
    
\
    <center>
   $$
U= \left[
\begin{array}{ccc}
\cos(\phi) & \sin(\phi) \\
-\sin(\phi) & \cos(\phi) \end{array}
\right]
$$
\
\
_Observe que:_ 
        $\cos(\phi) = c = 0.7071$ e $\sin(\phi) = s = 0.7071 $, logo a matriz de rotação é:

$$
U= \left[
\begin{array}{ccc}
0.7071 & 0.7071 \\
-0.7071 & 0.7071 \end{array}
\right]
$$
\
__Vamos aplicar a seguinte relação agora: $A_1 =  U^tAU $. A tendência é que sempre quando calculamos $U^tAU$ os elementos da diagonal principal de A tendem aos autovalores da matriz A inicial e os elementos fora da diagonal tendem a ser 0. Como é um processo iterativo a tendência é chegarmos nestes autovalores. Como a matriz A que estamos analisando é simples, vamos chegar agora nesses autovalores, todavia matrizes de ordens maiores o processo fica mais demorado e assim precisamos da ajuda de um algoritmo para executar essas iterações.__ 
        
__Observe que:__$$
U^t= \left[
\begin{array}{ccc}
0.7071 & -0.7071 \\
0.7071 & 0.7071 \end{array}
\right]
$$

__Então__ $A_1 = U^tAU\to$ 

$
A_1= \left[
\begin{array}{ccc}
4.9999041 & 0 \\
0 & 8.99982738 \end{array}
\right]
$
 
\
__Observe que essa matriz $A_1$ é uma matriz diagonal com autovalores $\lambda_1 = 4.9999$ e $\lambda_2 = 8.9998$__
        
\
__Abaixo, implementamos o método tal qual o usuário possa entrar com qualquer matriz e assim extrair os seus autovaloes.__
    



In [4]:
from math import*

import numpy as np

import scipy
import matplotlib.pyplot as plt
%matplotlib inline

__Abaixo há a implementação de duas funções, a função 'matriz_rotacao' gera a matriz U que foi discutida acima e a função 'gerador_matriz' que gera a matriz simétrica que queremos extrair os autovalores.__ 
\
\
_Vamos testar para a matriz 3x3 abaixo:_
\
   $$
x= \left[
\begin{array}{ccc}
4 & 2 & 0 \\
2 & 5 & 3 \\
0 & 3 & 6\end{array}
\right]
$$

In [7]:
def matriz_rotacao(n,p,q):
    u = np.eye(n)
    for i in range(len(u)):
        for j in range(len(u)):
            if i==p and j==q:
                u[p,q] = s    
                u[q,p] = -1*s
            elif i==j==p or i==j==q:
                u[p,p] = c
                u[q,q] = c
                
                
    return u  
def gerador_matriz(n):
    A= np.eye(n)
    A = np.matrix(A)
    for i in range(len(A)):
        for j in range(len(A)):
            if(i==j):
                A[i,j] = 0
    for i in range(len(A)):
        for j in range(len(A)):
            A[i,j] = input('Digite o elemento [%d,%d]' %(i,j))
            print(A)
    return A

n = int(input('Digite a ordem da matriz: '))
x = gerador_matriz(n)
autovalores = []
simetricax = []
simetricaxtransp = []

for i in range(len(x)):
    for j in range(len(x)):
        simetricax.append(x[i,j])
        simetricaxtransp.append(x.transpose()[i,j])
        
if(simetricax == simetricaxtransp):
    for i in range(0,1000000):


            lista = []

            for i in range(len(x)):
                for j in range(len(x)):
                    if(i!=j):
                        lista.append(x[i,j])
            
            for i in range(len(lista)):
                if(lista[i]<0):
                    lista[i] = -1*lista[i]
                else:
                    lista[i] = lista[i]
                
            
            maxi = max(lista)
            
            for i in range(len(x)):
                for j in range(len(x)):
                    if x[i,j] == maxi:
                        p = i
                        q = j

                        if p> q:
                            var = q
                            q = p
                            p = var
            
            

            l = 2*x[p,q]
            if(l!=0): #Critério de parada
                phi = (x[q,q] - x[p,p])/l


                if phi != 0:
                    if abs(phi+sqrt(phi**2+1))>abs(phi-sqrt(phi**2+1)):
                        den = phi+sqrt(phi**2+1)
                    else:
                        den = phi-sqrt(phi**2+1)
                    t = 1/den
                else:
                    t = 1

                c = 1/(sqrt(1+t**2))

                s = t/(sqrt(1+t**2))

                U = matriz_rotacao(n,p,q)



                x = U.transpose()*x*U

                for i in range(len(x)):
                    for j in range(len(x)):
                        x[i,j] = round(x[i,j],3)


            else:
                break
    i=0
    for j in range(len(x)):
        autovalores.append(x.diagonal()[i,j])
        print('Autovalor[%d] = %.4f' %(j,autovalores[j]))
else:
    print('As matrizes devem ser simétricas!')
        

 







Digite a ordem da matriz: 3
Digite o elemento [0,0]0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Digite o elemento [0,1]-1
[[ 0. -1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Digite o elemento [0,2]-1
[[ 0. -1. -1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Digite o elemento [1,0]-1
[[ 0. -1. -1.]
 [-1.  0.  0.]
 [ 0.  0.  0.]]
Digite o elemento [1,1]0
[[ 0. -1. -1.]
 [-1.  0.  0.]
 [ 0.  0.  0.]]
Digite o elemento [1,2]-1
[[ 0. -1. -1.]
 [-1.  0. -1.]
 [ 0.  0.  0.]]
Digite o elemento [2,0]-1
[[ 0. -1. -1.]
 [-1.  0. -1.]
 [-1.  0.  0.]]
Digite o elemento [2,1]-1
[[ 0. -1. -1.]
 [-1.  0. -1.]
 [-1. -1.  0.]]
Digite o elemento [2,2]0
[[ 0. -1. -1.]
 [-1.  0. -1.]
 [-1. -1.  0.]]
Autovalor[0] = 0.0000
Autovalor[1] = 0.0000
Autovalor[2] = 0.0000


In [9]:
x

matrix([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])

__Observe a matriz diagonal que o algoritmo conseguiu chegar, abaixo:__

In [41]:
x

matrix([[ 4.629,  0.184,  0.   ],
        [ 0.184,  1.52 , -0.653],
        [ 0.   , -0.653,  8.851]])

__Repare que se formos calcular $\phi$ chegaremos a um $\phi = \inf$ isso se deve pelo simples fato que que o elemento a<sub>qp</sub> = 0 e o quociente que calcula $\phi$ tem uma divisão por 0. Este foi o critério de parada definido no algoritmo__

__Para concluirmos que o algoritmo calculou com eficiência, temos que verificar se o determinante da matriz x é igual o determinante da matriz diagonal que foram achados os autovalores__ 

In [46]:
det_diag = np.linalg.det(x)
det_diag

60.00283736300002

__A matriz inicial foi:__
   $$
x= \left[
\begin{array}{ccc}
4 & 2 & 0 \\
2 & 5 & 3 \\
0 & 3 & 6\end{array}
\right]
$$

In [50]:
X = np.matrix([[4,2,0],[2,5,3],[0,3,6]])
det_init = np.linalg.det(X)
print('Matriz diagonal: %.4f Matriz Inicial: %.4f' %(det_diag,det_init))

Matriz diagonal: 60.0028 Matriz Inicial: 60.0000


__Observe que os determinantes foram aproximadamente iguais, garantindo a eficiência do algoritmo para matrizes simétricas 3x3__

__Agora vamos ver se o algoritmo detecta que a matriz deve ser simétrica__

In [31]:
def matriz_rotacao(n,p,q):
    u = np.eye(n)
    for i in range(len(u)):
        for j in range(len(u)):
            if i==p and j==q:
                u[p,q] = s    
                u[q,p] = -1*s
            elif i==j==p or i==j==q:
                u[p,p] = c
                u[q,q] = c
                
                
    return u  
def gerador_matriz(n):
    A= np.eye(n)
    A = np.matrix(A)
    for i in range(len(A)):
        for j in range(len(A)):
            if(i==j):
                A[i,j] = 0
    for i in range(len(A)):
        for j in range(len(A)):
            A[i,j] = input('Digite o elemento [%d,%d]' %(i,j))
            print(A)
    return A

n = int(input('Digite a ordem da matriz: '))
x = gerador_matriz(n)
autovalores = []
simetricax = []
simetricaxtransp = []

for i in range(len(x)):
    for j in range(len(x)):
        simetricax.append(x[i,j])
        simetricaxtransp.append(x.transpose()[i,j])
        
if(simetricax == simetricaxtransp):
    for i in range(0,1000000):


            lista = []

            for i in range(len(x)):
                for j in range(len(x)):
                    if(i!=j):
                        lista.append(x[i,j])
            
            for i in range(len(lista)):
                if(lista[i]<0):
                    lista[i] = -1*lista[i]
                else:
                    lista[i] = lista[i]
                
            
            maxi = max(lista)
            
            for i in range(len(x)):
                for j in range(len(x)):
                    if x[i,j] == maxi:
                        p = i
                        q = j

                        if p> q:
                            var = q
                            q = p
                            p = var
            
            

            l = 2*x[p,q]
            if(l!=0): #Critério de parada
                phi = (x[q,q] - x[p,p])/l


                if phi != 0:
                    if abs(phi+sqrt(phi**2+1))>abs(phi-sqrt(phi**2+1)):
                        den = phi+sqrt(phi**2+1)
                    else:
                        den = phi-sqrt(phi**2+1)
                    t = 1/den
                else:
                    t = 1

                c = 1/(sqrt(1+t**2))

                s = t/(sqrt(1+t**2))

                U = matriz_rotacao(n,p,q)



                x = U.transpose()*x*U

                for i in range(len(x)):
                    for j in range(len(x)):
                        x[i,j] = round(x[i,j],3)


            else:
                break
    i=0
    for j in range(len(x)):
        autovalores.append(x.diagonal()[i,j])
        print('Autovalor[%d] = %.4f' %(j,autovalores[j]))
else:
    print('A matrize deve ser simétrica!')
        

 




Digite a ordem da matriz: 4
Digite o elemento [0,0]2
[[2. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [0,1]3
[[2. 3. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [0,2]4
[[2. 3. 4. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [0,3]5
[[2. 3. 4. 5.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [1,0]6
[[2. 3. 4. 5.]
 [6. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [1,1]7
[[2. 3. 4. 5.]
 [6. 7. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [1,2]89
[[ 2.  3.  4.  5.]
 [ 6.  7. 89.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Digite o elemento [1,3]10
[[ 2.  3.  4.  5.]
 [ 6.  7. 89. 10.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Digite o elemento [2,0]12
[[ 2.  3.  4.  5.]
 [ 6.  7. 89. 10.]
 [12.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Digite o elemento [2,1]133
[[  2.   3.   4.   5.]
 [  6.   7.  89.  10.]
 [ 12. 133.   0.   0.]
 [  0.   0.   0.   0.]]
Digite o elemento [2,2]4
[[

__Veja que ele acusa que a matriz deve ser simétrica__

__Agora vamos ver um exemplo para matriz simétrica de ordem 4, definida abaixo:__
\
   $$
x= \left[
\begin{array}{ccc}
2 & 1 & 3 & 1 \\
1 & 0 &-1 & 0 \\
3 & -1 & 3 & 0\\
1 & 0 & 0 & 1\\
\end{array}
\right]
$$


In [74]:
def matriz_rotacao(n,p,q):
    u = np.eye(n)
    for i in range(len(u)):
        for j in range(len(u)):
            if i==p and j==q:
                u[p,q] = s    
                u[q,p] = -1*s
            elif i==j==p or i==j==q:
                u[p,p] = c
                u[q,q] = c
                
                
    return u  
def gerador_matriz(n):
    A= np.eye(n)
    A = np.matrix(A)
    for i in range(len(A)):
        for j in range(len(A)):
            if(i==j):
                A[i,j] = 0
    for i in range(len(A)):
        for j in range(len(A)):
            A[i,j] = input('Digite o elemento [%d,%d]' %(i,j))
            print(A)
    return A

n = int(input('Digite a ordem da matriz: '))
x = gerador_matriz(n)
autovalores = []
simetricax = []
simetricaxtransp = []

for i in range(len(x)):
    for j in range(len(x)):
        simetricax.append(x[i,j])
        simetricaxtransp.append(x.transpose()[i,j])
        
if(simetricax == simetricaxtransp):
    for i in range(0,1000000):


            lista = []

            for i in range(len(x)):
                for j in range(len(x)):
                    if(i!=j):
                        lista.append(x[i,j])
            
            for i in range(len(lista)):
                if(lista[i]<0):
                    lista[i] = -1*lista[i]
                else:
                    lista[i] = lista[i]
                
            
            maxi = max(lista)
            
            for i in range(len(x)):
                for j in range(len(x)):
                    if x[i,j] == maxi:
                        p = i
                        q = j

                        if p> q:
                            var = q
                            q = p
                            p = var
            
            

            l = 2*x[p,q]
            if(l!=0): #Critério de parada
                phi = (x[q,q] - x[p,p])/l


                if phi != 0:
                    if abs(phi+sqrt(phi**2+1))>abs(phi-sqrt(phi**2+1)):
                        den = phi+sqrt(phi**2+1)
                    else:
                        den = phi-sqrt(phi**2+1)
                    t = 1/den
                else:
                    t = 1

                c = 1/(sqrt(1+t**2))

                s = t/(sqrt(1+t**2))

                U = matriz_rotacao(n,p,q)



                x = U.transpose()*x*U

                for i in range(len(x)):
                    for j in range(len(x)):
                        x[i,j] = round(x[i,j],3)


            else:
                break
    i=0
    for j in range(len(x)):
        autovalores.append(x.diagonal()[i,j])
        print('Autovalor[%d] = %.4f' %(j,autovalores[j]))
else:
    print('A matrize deve ser simétrica!')
        

 




Digite a ordem da matriz: 4
Digite o elemento [0,0]2
[[2. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [0,1]1
[[2. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [0,2]3
[[2. 1. 3. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [0,3]1
[[2. 1. 3. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [1,0]1
[[2. 1. 3. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [1,1]0
[[2. 1. 3. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Digite o elemento [1,2]-1
[[ 2.  1.  3.  1.]
 [ 1.  0. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Digite o elemento [1,3]0
[[ 2.  1.  3.  1.]
 [ 1.  0. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Digite o elemento [2,0]3
[[ 2.  1.  3.  1.]
 [ 1.  0. -1.  0.]
 [ 3.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Digite o elemento [2,1]-1
[[ 2.  1.  3.  1.]
 [ 1.  0. -1.  0.]
 [ 3. -1.  0.  0.]
 [ 0.  0.  0.  0.]]
Digite o elemento [2,2]3
[[ 2.  1.  3.  1.]
 [

__Veja que os autovalores são__ $\lambda_0 = 3.0000$, $\lambda_1 = 0.0000$, $\lambda_2 = -0.2500$,$\lambda_3 = 1.000$

In [68]:
A = np.matrix([[2,1,3,1],[1,0,-1,0],[3,1,3,0],[1,0,0,1]])

In [79]:
detx = np.linalg.det(x)
detA = np.linalg.det(A)

In [80]:
print('Matriz diagonal: %.4f Matriz inicial: %.4f' %(detx,detA))

Matriz diagonal: -2.5017 Matriz inicial: -2.0000


<p><i>Veja que os valores são aproximadamente próximos, todavia o erro é maior que para uma matriz 3x3</i></p>

<p><b>MÉTODO SIMPLEX</b></p>

<p><i><div align="justify">O algoritmo SIMPLEX dispõe-se de um método iterativo para ser realizado, possuímos uma função chamada função objetivo e algumas restrinções. O SIMPLEX se baseia na álgebra linear para determinar por meio de várias iterações, uma solução ótima de um Problema de programação linear. O algoritmo parte de uma solução inicial, a partir dessa solução vai identificando novas soluções viáveis de valor igual ou melhor. Dois critérios são definidos, um de escolha que permite encontrar sempre novos e melhores vértices da envoltória convexa do problema e um outro método que vai determinar se o vértice é ótimo ou não. A figura geométrica que representa o espaço de soluções é um politopo e neste politopo temos uma região factível. O procedimento se dá da seguinte forma:</div> </i></p>
<i>
<ol>
    <li>Inversão de uma matriz base $mxm $ deduzida a partir de uma matriz A($mxn$).</li>
     <li>Troca de colunas da matriz base com objetivo de melhorar a solução básica por meio das iterações.</li>
    <li>E por fim a Regra de parada.</li>

</ol>
</i>
 


<p><i>Para explicarmos melhor o método precisamos ter a noção que é possível decompor o vetor das varíaves $x$ em $x = (x_B,x_R)$ onde:</i></p>
<ol>
    <li> $x_B$ é o vetor das variáveis básicas de m componentes.</li>
    <li> $x_R$ é o vetor das varíaveis não básicas de $n-m$ componentes.</li>
 </ol>
 
 <p> Os elementos de indíce $I$ e $J$ são para diferenciar as variáveis básicas e não básicas, respectivamente.</p>
 
 <p>Quando $B$ é uma matriz base associada à matriz $A$. O vetor composto $x_b = B^-1b e x_r = 0 $ é chamada solução básica ou ponto extremo do conjunto do sistema $Ax = b$.
        <p><i>Quando a solução não apresenta componentes negativas é chamada de solução básica viável.</i></p>.
     <p> Além da solução básica, é possível também melhorar a variável básica. Por meio de algumas operações podemos reescrever $x_b, b^-1b e y_k$ da seguinte forma:
    $x_B = b^-1b - y_kx_k$ onde $y_k = B^-1a_k$
     

<p><b>MÉTODO SIMPLEX DE DUAS FASES </b></p>

 <p><i>É um procedimento para zerar as variáveis de folga. A fase 1 visa obtenção de uma solução básica viável para o PPL. Na fase 2 com a solução básica factível, aplica-se o SIMPLEX no problema original.</i></p>

<b>FASE 1</b>

<p>Considere o problema genérico abaixo:</p>
$$\phi = 1 \\
Ax + x_a = b \\
x, x_a \ge 0 
$$

<p>Resolvendo o problema genérico acima pelo SIMPLEX. Se o valor ótimo deste problema for $\phi = 0 $ então a solução ótima correspondente é uma solução básica factível inicial do problema original.</p>
    <p>Se o valor ótimo de $\phi$ é positivo o problema original não tem solução factível. A solução do problema acima pode ter $x_a = 0 $, mas pode ser que alguma variável artificial esteja na base com valor zero.

<b>DEGENERAÇÃO E CICLAGEM</b>


<p>O algoritmo converge das várias reduções que acontece, devido ao critério de escolha de troca de uma variável, isso melhora o valor da função objetivo. O algoritmo pode chegar em situações que pode ter um comportamento que não siga os critérios anteriores. Isso pode acontecer quando $z_j - c_j$ associadas a algumas variáveis possuem valores iguais e o mesmo acontece ao valor mínimo.</p>